### ISSUE TITLE
can't find the gradle

### ISSUE THREAD

**Issue by pavelsust** [ldt116/FBNativeAdAdapter#1]
It shows that Error:(102, 13) Failed to resolve: me.timos.thuanle:fb-native-ad-adapter:latest.version

**Comment by ldt116** [comment]
Latest version is `1.3.2`.

Please use `me.timos.thuanle:fb-native-ad-adapter:1.3.2`

**Comment by nilesh52** [comment]
I have just try to install library and its shows below error,
ERROR: Failed to resolve: com.facebook.android:audience-network-sdk:4.+

early it was working, but now throwing error

**Comment by pavelsust** [comment]
this library need to update facebook audience version to 5+

**Comment by nilesh52** [comment]
Hi,
I have attached screenshot.
Library already updated.
actually this fb-native-ad-adapter was working fine before  month.
I think recently change of fb sdk affected.

Can u please help on this.

![Error](https://user-images.githubusercontent.com/40433354/60766686-1e612900-a0cb-11e9-994b-43dbe30c1af4.PNG)

**Comment by pavelsust** [comment]
[fb-native-ad-adapter.zip](https://github.com/ldt116/FBNativeAdAdapter/files/3374434/fb-native-ad-adapter.zip)

Import this as a gradle into your project and start working

**Comment by nilesh52** [comment]
thanx
